### ISSUE TITLE
Calculator example, unary operators

### ISSUE THREAD

**Issue by hia3** [ColinH/PEGTL#16]
Calculator example can't parse "-(5+5)".

**Comment by d-frey** [comment]
Hi Colin,

das war eines von Deinen Beispielen, oder? Wenn ich es richtig sehe gibt es nur binäres Minus und negative Zahlen, aber keinen generischen unären Operator - zum Negieren eines Ausdrucks. Für ein Beispiel OK, andererseits... wenn es einfach ist kannst Du es natürlich gerne hinzufügen. :)

Liebe Grüße,
Daniel

**Comment by ColinH** [comment]
For simplicity, the calculator example doesn't currently implement unary operators (except for signs that are part of an integer literal).

**Comment by ColinH** [comment]
In case you opened this issue because you are interested in how to handle unary operators in the calculator example, which is not quite trivial, you can contact us at `pegtl(at)colin-hirsch.net`.

**Comment by hia3** [comment]
Thanks :-)

But I was just reading the example and thought that this might be omission. If this is as intended, I'm okay with that.
