### ISSUE TITLE
The README hello world is not up-to-date with the source

### ISSUE THREAD

**Issue by RasmusFonseca** [ColinH/PEGTL#23]
When running the hello world in the README.md I get:

```
/Users/rfonseca/Documents/workspace-CPP/SeqScan/src/testpegtl.cc:84:35: error: no type named 'input' in namespace 'pegtl'
  static void apply( const pegtl::input & in, std::string & name )
                           ~~~~~~~^
```

**Comment by ColinH** [comment]
Yes, the documentation is up-to-date with the last release, but not with the master branch. We'll "fix" this with the next release really soon.

**Comment by ColinH** [comment]
The documentation is now updated to better reflect the master-branch. There are still things missing, but the issue you reported is now fixed.

**Comment by RasmusFonseca** [comment]
:thumbsup:
