### ISSUE TITLE
Calculator example priority issues

### ISSUE THREAD

**Issue by cpcdoy** [ColinH/PEGTL#26]
The calculator does not yield the same result for : 100-100x3+111 (which gives -311) and for : 100-(100x3)+11 (which gives -89)

**Comment by tomilov** [comment]
@cpcdoy What is "calculator"?

**Comment by kirbyfan64** [comment]
https://github.com/ColinH/PEGTL/blob/master/examples/calculator.cc

**Comment by tomilov** [comment]
Maybe associativity hadled wrongly?

**Comment by cpcdoy** [comment]
I guess it is handled wrongly

**Comment by ColinH** [comment]
Thank you for reporting the issue, it is now fixed.
