### ISSUE TITLE
Include paths problem on OSX

### ISSUE THREAD

**Issue by cbossut** [ColinH/PEGTL#3]
Hi !

I was unable to compile on OSX due to the compiler not finding the file type_traits, and I found that it needs the -stdlib option set to libc++ to look in the good places.

I suggest adding it to the Makefile, as I've done, if it doesn't break compiling on other OSs.

**Comment by d-frey** [comment]
What version of OSX and what compiler / compiler version are you using? For me, the included Makefile works on OSX 10.10.2 without problems.

**Comment by kirbyfan64** [comment]
http://stackoverflow.com/a/14229045/2097780

Apparently, even slightly older Macs have older versions of libstdc++; using Clang+libc++ is recommended.

**Comment by d-frey** [comment]
I added support for (older versions of) Mac OS X. Please report back if it does not fix the problem or in case I broke something else.
