### ISSUE TITLE
Can you please create install instructions?

### ISSUE THREAD

**Issue by BoredBored** [ColinH/PEGTL#39]
I'v downloaded this on my laptop (running Ubuntu) and I was wonder -- how can I Install this?

**Comment by d-frey** [comment]
We have installation instructions in the documentation, e.g., at https://github.com/ColinH/PEGTL/blob/master/doc/Getting-Started.md#compilation

The short version is: It's a header-only library, there is nothing to install. Just copy the files somewhere and add it to your compiler's include path.

There are also packages available for several recent distributions, so you might also check with your distribution's package manager. If you install a package, it is available for use without adding an include path to the compiler explicitly, just make sure you are using the appropriate flags for C++11 or newer.
