### ISSUE TITLE
Problem compiling s_expression_2 example

### ISSUE THREAD

**Issue by cbossut** [ColinH/PEGTL#4]
Hello again,

I have an error while compiling the example s_expression_2 that I don't understand :

c++ -I. -std=c++11 -stdlib=libc++ -pedantic -Wall -Wextra -Werror -O3 examples/s_expression_2.cc -o build/examples/s_expression_2
examples/s_expression_2.cc:74:32: error: no matching member function for call to 'parse'
         read_parser( fn, in ).parse< main, action >( f2 );
         ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
./pegtl/read_parser.hh:39:12: note: candidate template ignored: invalid explicitly-specified argument
      for template parameter 'Action'
      void parse( States && ... st )
           ^
1 error generated.
make: *** [build/examples/s_expression_2] Error 1

**Comment by d-frey** [comment]
The code used `action` within a method of the class template, hence it is the full type, not the class template. Fixed the illegal code by using `sexpr::action`.
