### ISSUE TITLE
Is there an easy way to obtain the position *range* of a matched PEG expression?

### ISSUE THREAD

**Issue by skyrich62** [ColinH/PEGTL#44]
Hi,
Currently, I have action<> specializations with apply() method to acquire the matched text, eg:

```c++
template<> struct action<number>
{
    template <typename Input>
    static void apply(const Input &in, SomeState &state)
    {
         // here I capture the text via "in.string()", and the starting position via "in.position()"
         ...
    }
};
```
Is there an easy way to obtain the position at the end of the matched text?
Right now, I'm iterating over the string, increment byte, and byte_in_line, (unless I see a newline), in which case, I bump the line counter, and reset the byte_in_line counter.  It occurs to me that the parser must already have this information somewhere, and I'm just wasting CPU cycles. :(

Also, I have a small "calculator" project which creates and AST from the input, then evaluates the AST to perform the calculations.  Let me know if you're interesting in seeing it.
--Rich

**Comment by ColinH** [comment]
Hi, first off, thank you, we are always interested in seeing what other people do with the PEGTL, and how they use it! We are reachable here, or email to pegtl(at)colin-hirsch.net.
Regarding your question, it is not directly possible to obtain the end position information, the parser does have this information but does not pass it to the action.
As a simplification, you could instantiate a new input in the action and call its `bump()`-method, then at least you don't have to replicate the counting logic.
We don't want to pass this additional information to all actions, however we could pass it to a new control method for `apply()`, and let the control method perform the final steps of action invocation.
Then you could change the control-class to give you everything that you need. I will look into this with @d-frey .

**Comment by ColinH** [comment]
Actually this was such an easy and obvious fix, I just committed it to the master branch. You can now supply your own `control<>` class template that uses the `input_mark` and the input supplied to its `apply()`-method to pass both positions to the action. It might be a bit fiddly, but the information is all there.
