### ISSUE TITLE
input wrapping issue

### ISSUE THREAD

**Issue by balkamm** [ColinH/PEGTL#5]
There seems to be some internal wrapping mechanism when working with large input strings.  I see several lines in the trace which look like this:

```
pegtl: success flags 1 rule    1 nest   1 at 15,23 expression ...
pegtl: start   flags 2 rule    1 nest   1 at 1,1 expression ...
```

I'm occasionally experiencing a bug where a rule which works otherwise doesn't work immediately following one of these discontinuities.  I can try to work up a minimal example if that would help.

**Comment by d-frey** [comment]
A minimalistic example would be most helpful.

**Comment by balkamm** [comment]
The only document that I've gotten it to fail on is slightly personal.  Would it be possible to share it with you off list?

**Comment by ColinH** [comment]
Sure, you can send us an e-mail to *pegtl (at) colin-hirsch.net* and we'll take a look...

**Comment by d-frey** [comment]
Closed as requested by submitter, seems the bug was not in the PEGTL. Matthew, please feel free to re-open it if necessary.
