### ISSUE TITLE
Win32 compile errors

### ISSUE THREAD

**Issue by CaptainZippy** [ColinH/PEGTL#8]
Hi, great to see the new project structure & hosting! Have you any interest in making pegtl work on win32? Here's a quick sample of some of the issues I found:

Warnings:
* not all control paths return a value (unhex_char, unescape_c)
* a number of warnings about buffer overruns (see the end for a sample)

Most other issues seem to be related to partial c++11 support.

* inline namespace not supported (ascii.hh)
* pegtl\examples\json_build_one.cc(93): error C2783: 'std::shared_ptr<_Ty> std::make_shared(_Types &&...)' : could not deduce template argument for '_Ty'
 

11>s:\source\pegtl\pegtl\internal\rule_conjunction.hh(21): warning C4789: buffer '' of size 4 bytes will be overrun; 1 bytes will be written starting at offset 4
11>s:\source\pegtl\pegtl\internal\rule_conjunction.hh(21): warning C4789: buffer '' of size 4 bytes will be overrun; 1 bytes will be written starting at offset 5
11>s:\source\pegtl\pegtl\internal\sor.hh(26): warning C4789: buffer '' of size 4 bytes will be overrun; 1 bytes will be written starting at offset 4
11>s:\source\pegtl\pegtl\internal\sor.hh(26): warning C4789: buffer '' of size 4 bytes will be overrun; 1 bytes will be written starting at offset 4
11>s:\source\pegtl\pegtl\internal\rule_conjunction.hh(21): warning C4789: buffer '' of size 4 bytes will be overrun; 1 bytes will be written starting at offset 4
11>s:\source\pegtl\pegtl\internal\rule_conjunction.hh(21): warning C4789: buffer '' of size 4 bytes will be overrun; 1 bytes will be written starting at offset 5
11>s:\source\pegtl\pegtl\internal\rule_conjunction.hh(21): warning C4789: buffer '' of size 4 bytes will be overrun; 1 bytes will be written starting at offset 6

**Comment by samhocevar** [comment]
Note from another Win32 user: the warnings only occur in Debug builds as far as I know. In Release builds, once the optimiser kicks in, it understands that the buffers aren’t actually used at all, and the warnings disappear.

If you’re trying to build PEGTL with Visual Studio 2013, I believe it’s basically hopeless. There is no way VS2013 can understand the code. From my last attempts, here are the necessary features that are missing: nullptr, constructor inheritance, deleted default members, SFINAE based on decltype, templated "using", template template parameters.

If you are using Visual Studio 2015, the code should compile just fine. I have [a forked repository](https://github.com/samhocevar/pegtl) with a `.sln` and the necessary `.vcxproj`.

**Comment by ColinH** [comment]
Assuming that Sam's post explains what's going on I'm closing this issue; we are however following up on this and will send a bug report in the direction of MS regarding the wrong warning.

The new PEGTL will never work on VS2013, but we are interested in VS2015 compatibility, and thanks to previous help and feedback from Sam it does actually work now.

**Comment by CaptainZippy** [comment]
Thanks for the explanation. If it wasn't a big deal, it would be nice not to have to rely on newer C++ features but I appreciate that there is a tradeoff and working around missing features can be pretty tedious.

**Comment by d-frey** [comment]
In order to report to problem towards Microsoft: Could you please check if the following program produces the same warning in Debug-mode? And if it can be reduced further? TIA!

void dummy( int ) {}

template< int... Is >
void test()
{
  using swallow = bool[];
  (void)swallow{ ( dummy( Is ), true )... };
}

int main()
{
  test< 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 >();
}
